library identifier: 'bootcamp-devops-jenkins-library@main',
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/monicacrespo/bootcamp-devops-jenkins-library.git'])

pipeline {
    agent any
    stages {
        stage('Audit tools') {
            steps {
                auditTools()
            }
        }
    }
}